language: python
python:
    - "2.6"
    - "2.7"
script: nosetests
branches:
    only:
        - master
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-augeas
install: "pip install ."
