language: python
python:
    - "2.6"
    - "2.7"
script: nosetests
branches:
    only:
        - master
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-augeas python-mysqldb python-lxml python-netifaces python-ipy
install: "pip install ."
