#!/bin/bash
# From HERE, it finds all modules and creates dot and svg lifecycle representation.
# Generated file are stored in doc/source/_images directory.
# Moreover, it generates a modules rst file which is included by index.rst

# The name of the module lifecycle class must be the same than the
# module directory name with the first letter in upper case. For instance:
# armonic/modules/apache with armonic.modules.apache.Apache classe.

echo "Generating svg file for all armonic modules"

image_path="source/_images"
mkdir -p ${image_path}

rst_module_file="source/modules.rst"
echo ".. Generated by generate_module_doc" > ${rst_module_file}
echo ".. Don't edit it!" >> ${rst_module_file}
echo ".. It will be erased on next shinx doc generation." >> ${rst_module_file}
echo "" >> ${rst_module_file}
echo "armonic modules documentation" >> ${rst_module_file}
echo "=============================" >> ${rst_module_file}
modules=$(find ../armonic/modules/*  -maxdepth 1 -type d)

for path in $modules
do
    module=$(basename ${path})
    lifecycle=$(echo $module | sed '1s/^\s*./\U&\E/g')

    echo "Generating json file for module"${lifecycle}.dot
    json_file_path=${image_path}/${module}.json
    python -c "import armonic.modules.${module}  ; import pprint ; pprint.pprint(armonic.modules.${module}.lifecycle.${lifecycle}().to_primitive())" 2>/dev/null 1>${json_file_path}
    if [ $? -eq 0 ]
    then
	echo "  json file for ${module} has been created"
    else
	echo "  json file for ${module} cannot be genereted"
	rm $json_file_path
    fi



    echo "Generating svg file for module "${lifecycle}.dot
    dot_file_path=${image_path}/${module}.dot
    python -c "import armonic.modules.${module}  ; print armonic.modules.${module}.lifecycle.${lifecycle}().to_dot()" 2>/dev/null 1>${dot_file_path}
    if [ $? -eq 0 ]
    then
	echo "  dot file for ${module} has been created"
	dot -Tsvg ${dot_file_path} 2>/dev/null 1> ${image_path}/${module}.svg
	echo "  svg file for ${module} has been created"

	echo "Module ${lifecycle}
----------------------------------------

.. automodule:: armonic.modules.${module}
    :members:

.. figure:: _images/${module}.svg
   :width: 200px
   :height: 400px
   :target: _images/${module}.svg
   :align: center

   Graphical representation of ${module} lifecycle.

" >> ${rst_module_file}


    else
	echo "  dot file for ${module} cannot be genereted"
	rm $dot_file_path
    fi
done


